#!/usr/bin/env bash

echo 'Welcome to sum two number'

read -p "Enter first number: > " first_number
read -p "Enter second number: > " second_number
read -p "Choose operator [+, -, *, /]: > " operator

operation_name=
result=
if [ "$operator" = '+' ]; then
    operation_name='sum'
    result=$((first_number + second_number))
elif [ "$operator" = '-' ]; then
    operation_name='substraction'
    result=$((first_number - second_number))
elif [ "$operator" = '*' ]; then
    operation_name='multiplication'
    result=$((first_number * second_number))
elif [ "$operator" = '/' ]; then
    operation_name='division'
    result=$((first_number / second_number))
fi

echo "The $operation_name of $first_number and $second_number is $result"