#!/usr/bin/env bash

echo 'Welcome to simple math, my absolute first shell script!'

read -p "Enter first number: > " first_number
read -p "Enter second number: > " second_number
read -p "Choose operator [+, -, *, /]: > " operator

operation_name=
result=
case $operator in
    + )
    operation_name='sum'
    result=$((first_number + second_number))
    ;;
    - )
    operation_name='substraction'
    result=$((first_number - second_number))
    ;;
    * )
    operation_name='multiplication'
    result=$((first_number * second_number))
    ;;
    / )
    operation_name='division'
    result=$((first_number / second_number))
    ;;
    * ) echo 'You broke it. Do you feel good?'
    exit 1;
esac

echo "The $operation_name of $first_number and $second_number is $result"
exit 0